### ISSUE TITLE
Error al abrir programas

### ISSUE THREAD

**Issue by 0xParanoia** [RaulSanchezzt/kali-bspmw#1]
Cuando abres una terminal o lo que sea en el espacio de trabajo número 1 se abre en el 2 y asi con los demas

**Comment by RaulSanchezzt** [comment]
Hola, sí estás usando mis [dotfiles](https://github.com/RaulSanchezzt/dotfiles/tree/bspwm), está configurado así en el archivo [bspwmrc](https://github.com/RaulSanchezzt/dotfiles/blob/bspwm/bspwm/bspwmrc). Puedes eliminar estas reglas si quieres para que se abran las ventanas en el espacio de trabajo actual.

```bash
# Web Proxy: BurpSuite
bspc rule -a burp-StartBurp desktop='^1' follow=on focus=on
# Terminal: Kitty
bspc rule -a kitty desktop='^2' follow=on focus=on
# Web Browser: Firefox
bspc rule -a Firefox-esr desktop='^3' follow=on focus=on
# File Explorer: Thunar
bspc rule -a Thunar desktop='^4' follow=on focus=on
# IDE: Visual Studio Code
bspc rule -a Code desktop='^5' follow=on focus=on
# Markdown Editor: Obsidian
bspc rule -a obsidian desktop='^5' follow=on focus=on
```
